language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: moira-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: moira-springboot
    key : MOIRA.zip

    bundle_type : zip
    application : MOIRA

    deplyment_group : moira-group
    region: ap-northeast-2
    wait-until-deployed : true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kimsw1726@gmail.com